recallnet/js-recall

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/version.yml
package.json

- We use `version.yml` to auto-create version PRs whenever the `.changesets` directory is updated upon merging to main.
- This only happens if you stage a new release via the `pnpm changeset` command locally, which will create markdown file(s) in `.changesets` that describe the semver change and relevant packages.
- When you merge these `.changesets` markdown files to main, a PR is opened, which deletes these changeset files, creates/updates the `CHANGELOG.md` files with their contents, and updates each package's `package.json` file's semver accordingly.
- If an existing version PR is open, and you merge more staged changesets into main, it'll automatically keep updating the PR.
- An example of what this looks like is https://github.com/recallnet/js-recall/pull/57. 
- Upon merging the PR …

chore: release workflow changes

---

.changeset/config.json

force `@recallnet/sdx` to _not_ be included in the changeset. it seems the `updateInternalDependencies` will (for some reason) also bump packages, even if they're not explicitly included in the changeset release.

chore: remove sdx from changeset

---

.changeset/eleven-moose-tease.md
packages/sdk/package.json
packages/sdk/src/network.ts
packages/sdk/test/client.test.ts
packages/sdk/test/contracts.test.ts
packages/sdk/test/network.test.ts

the `dist` folder outputs a flat map, which changed recently (used to be nested `entities` folder). this didnt trigger testing errors locally due to legacy `dist` deps, and we dont have a testing CI flow, so it was never caught.

fix: `sdk` exports

---

.changeset/nasty-pets-sleep.md
packages/network-constants/src/index.ts

RPCs can now use the stable RPC/API format instead of versioned subdomain

feat: update RPCs

---

.zed/settings.json
package.json
packages/address-utils/package.json
packages/bigint-utils/package.json
packages/chains/package.json
packages/contracts/package.json
packages/fvm/package.json
packages/network-constants/package.json
packages/sdk/package.json
packages/sdkx/package.json

Something seemed off about our package exports and ts types. I noticed that `tsup` was outputting special ts types for cjs that we weren't referencing. Some research and this tool Are the Types Wrong (https://arethetypeswrong.github.io/?p=@recallnet/sdk@0.0.4 and the cli command `pnpm dlx @arethetypeswrong/cli --pack`) helped me understand what was going on and what the correct configuration should be.

Correct use of package.json exports and tsc/tsup output

---

.changeset/afraid-parents-peel.md
packages/chains/package.json
packages/contracts/src/index.ts
packages/sdk/package.json
pnpm-lock.yaml

note: we'll want to merge / release packages once the new testnet is up. the changes include:
- bump the `contracts` submodule, which includes the changed `MachineInitialized` event. this event is only used by the `sdk` package's `createBucket` event parsing.
- update the `sdk` and `chains` packages to use `viem@^2.22.9` since this is what other monorepo packages are using
closes https://github.com/recallnet/js-recall/issues/59.

feat: update `contracts` event for testnet v0.1.4

---

.changeset/popular-bulldogs-fry.md
packages/chains/src/index.ts

increases the default [base fee multiplier](https://viem.sh/docs/chains/fees#feesbasefeemultiplier) from 1.2 to 120, which more closely matches what we see with `forge script` contract deployments (i.e., 100x-1000x the default).
this _should_ resolve [issues mentioned](https://discord.com/channels/1229504999910801469/1229514067169906819/1349548754126245928) about out of gas RPC errors. this happens if the gas estimation is incorrect. it generally doesnt occur for simple txs, but we've seen a couple of users report it:
note: i personally wasnt able to recreate the issue, and it's not clear why or when this occurs

feat: default chain base fee multiplier

---

packages/agent-toolkit/package.json
packages/mcp/.env.example
packages/mcp/README.md
packages/mcp/eslint.config.js
packages/mcp/package.json
packages/mcp/src/config.ts
packages/mcp/src/index.ts
packages/mcp/tsconfig.json
packages/mcp/tsup.config.ts
pnpm-lock.yaml

Add an official `@recallnet/mcp` binary that can be ran with `npx`.
- The design is, basically, unchanged from the [agent toolkit example](https://github.com/recallnet/js-recall/blob/main/packages/agent-toolkit/examples/mcp.ts) MCP server
- You can test the tool out by building and then running `node dist/index.js --private-key=0x...` (or by setting the RECALL_PRIVATE_KEY env var). Just make sure you're explicit since it won't be read from any `.env.` file.
- The docs are pretty light and just point to the docs site, which we can update later

feat: mcp server

---

apps/portal/app/buckets/[address]/_components/object.tsx

The path usually includes `/` delimiters which shouldn't be encoded because they are the url path structure that the objects api expects in order to look up objects.
Ideally, we'd encode each component of the path, excluding the `/`, and use that to build the URL, but the object api doesn't seem to support URL ecdoded values, so it just returns not found in that case. Basically, we need to fix the object api then we can make more improvements here.
Closes #187

Don't url encode entire path

---

.changeset/fair-spoons-teach.md
packages/network-constants/src/index.ts

see merged PR for the values: [here](https://github.com/recallnet/recall-docker-compose/pull/43/files#diff-79f0c66c7bd0b988945aeb7033864f0d4057400fd078b7eb1069cdaf345cf72aR7-R18). this also updates the faucet url to the new `registrar` subdomain.
```toml
subnet_id="/r314159/t410fntaew3dtef2zpfox2hlhy4cgrksdt5zjwg3hbfi"
parent_gateway_address="0x2758f99EaB8ea9B8678B5d841851D62Ef18AAB26"
parent_registry_address="0xE8090d55E7ecc0565830845Df67bfD3fA81D4158"
parent_supply_source_address="0xd1239c6b6f806EC3752df12CEaddD88187BCf1E5"
subnet_credit_manager_address="0x296042865b783D8E8Fb09F04FFAE2A66a16B85Bc"
subnet_bucket_manager_address="0x170a22c76a2Bb7c5F1b0e7067a0ddb7C3452c8e0"
subnet_faucet_contract_address="0x19e99fB563CD187fC9e2D0dd204D2c0aD3a87Adc" …
```

feat: testnet v0.1.6

---

.changeset/common-bags-sink.md
packages/agent-toolkit/README.md
packages/agent-toolkit/eslint.config.js
packages/agent-toolkit/examples/mcp.ts
packages/agent-toolkit/examples/openai.ts
packages/agent-toolkit/package.json
packages/agent-toolkit/src/ai-sdk/toolkit.ts
packages/agent-toolkit/src/langchain/tool.ts
packages/agent-toolkit/src/langchain/toolkit.ts
packages/agent-toolkit/src/mcp/toolkit.ts
packages/agent-toolkit/src/openai/toolkit.ts
packages/agent-toolkit/src/shared/api.ts
packages/agent-toolkit/src/shared/configuration.ts
packages/agent-toolkit/src/shared/functions.ts
packages/agent-toolkit/src/shared/index.ts
packages/agent-toolkit/src/shared/parameters.ts
packages/agent-toolkit/src/shared/prompts.ts
packages/agent-toolkit/src/shared/tools.ts
packages/chains/src/index.ts
packages/mcp/README.md
packages/mcp/src/config.ts
pnpm-lock.yaml

- alter the add/get object methods to _only_ work with string values input/output values. 
- e.g., the types were too flexible when adding or getting an object (Uint8Array, File, or string/path), and agents were getting confused on how to write or read data.
- move function call definitions into the `tools` vs handling logic in the `RecallAPI` (this also makes each tool's function more easily).
- include `getTools` on the Recall API so that agent toolkit instances can use it directly when setting up tools.
- allow `prompts` and `parameters` to accept the `context` arg. 
- we don't do anything with this yet, but it'll set us up for future features, like injecting bucket aliases or competition / agent config data into an agent's prompt.
```ts
export const getOrCreateBucketPrompt = …
```

feat: agent toolkit logic tweaks

---

.changeset/loud-plums-share.md
packages/network-constants/src/index.ts
packages/sdk/src/entities/account.ts
packages/sdk/src/entities/blob.ts
packages/sdk/src/entities/bucket.ts
packages/sdk/src/entities/credit.ts
packages/sdk/src/errors.ts
packages/sdk/src/ipc/gateway.ts

closes https://github.com/recallnet/js-recall/issues/202 https://github.com/recallnet/recall-alpha-agent/issues/7. 
for the issue where we're burning through RECALL tokens, all we need to do is manually make the `getGasPrice` call before every write operation, and then pass it as an option to the method call:
```ts
const gasPrice = await this.client.publicClient.getGasPrice()
const hash = await this.client.walletClient?.sendTransaction({
account: this.client.walletClient.account,
chain: this.client.walletClient.chain,
to: recipient,
value: amount,
gasPrice,
});
```
for the query objects issue, we do the following:
1. set a MAX_QUERY_LIMIT to 50 objects because if you try to make a query larger than that, there's a high likelihood it'll fail (out of gas issues due to onchain processing)
2. …

feat: fix gas estimation & query limit issues

---

.changeset/evil-areas-divide.md
packages/sdk/src/client.ts

- Alter the `walletClientFromPrivateKey` to allow for a raw string value that can be `0x` or non-`0x` prefixed, making it more flexible for ppl to use. (Before, it only worked if `0x` prefixed.)
- Add a new static `fromPrivateKey` method so that you can just instantiate a `RecallClient` from a private key value, instead of having to set up the wallet client and pass that in the constructor.
- Make `testnet` the default chain in `fromPrivateKey`, `walletClientFromPrivateKey`, and `createPublicClientForChain`. This eliminates the need to also install/import the `@recallnet/chains` package, unless you want to override the default.

feat: allow hex or non-hex private key

---

apps/api/e2e/tests/rate-limiter.test.ts
apps/api/src/middleware/errorHandler.ts

- Somehow with the turbo-related changes some of my error responses were defaulting to html
- Fixed by standardizing in error handler

fix: remove html error responses

---

apps/api/e2e/tests/team.test.ts
apps/api/e2e/tests/trading.test.ts
apps/api/e2e/utils/api-client.ts
apps/api/e2e/utils/api-types.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/package.json
apps/api/src/controllers/account.controller.ts
apps/api/src/middleware/admin-auth.middleware.ts
apps/api/src/middleware/auth.middleware.ts
apps/api/src/routes/account.routes.ts
apps/api/src/services/team-manager.service.ts

- Allows teams to reset their api keys, thus updating the `updatedAt` and `apiKey` fields in their corresponding entry in the `teams` table
- Updates the apiKeyCache
- Provide a new test case in team.test.ts e2e test to validate functionality
- Regenerated openapi docs given the route change to accounts
- Moved openapi references to location that would be included by git
- Add missing test case for trade reason

feat: allow teams to reset their api keys

---

apps/api/e2e/tests/competition.test.ts
apps/api/e2e/utils/api-client.ts
apps/api/e2e/utils/api-types.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/src/controllers/competition.controller.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/routes/competition.routes.ts
apps/api/src/services/competition-manager.service.ts

- Adds a new route to apps/api/src/routes/competition.routes.ts that allows authenticated teams to fetch upcoming competitions (marked as PENDING in the db)
- Adds a new method to apps/api/src/controllers/competition.controller.ts that utilizes the competition manager service to fetch upcoming competitions, and also implements the authentication gating (same pattern as the other controllers)
- Implements a new method in apps/api/src/services/competition-manager.service.ts to use the competition repository's `findByStatus` method
- Implements `findByStatus` in apps/api/src/database/repositories/competition-repository.ts using the same pattern matching as the other repository methods to access the data layer
- Updates api-client, types, and competition.test.ts in apps/api/e2e to confirm …

feat: add ability to get upcoming (pending) competitions

---

.github/workflows/api-ci.yml
.gitignore
apps/api/e2e/tests/portfolio-snapshots.test.ts
apps/api/e2e/tests/price/chain-detection-debug.test.ts

- Test wrapper in api-ci was mistakenly configured to exit and pass instead of correctly noting when tests fail and therefore fail the larger job
- This change updates the script accordingly in api-ci, and allows more leniency in `portfolio-snapshots.test.ts` when it comes to testing portfolio value closeness calculations (as the previous settings were too rigid and intermittently caused tests to fail)
- The new script tracks individual tests in memory - if any fail, the job fails. Otherwise, the job passes if all test cases pass

fix: update api-ci to correctly exit when tests fail

---

.gitignore
apps/api/e2e/utils/log-reporter.ts
apps/api/vitest.config.ts

- Reverts json log reporting (sorry)
- Updates log-reporter to write results to log file
**Note**: Does not output individual test cases between each test file like previous version, but I think that's fine for now

fix: updates log-reporter to output results in log file

---

apps/registration/app/page.tsx
apps/registration/components/agent-registration-form.tsx
apps/registration/components/registration-success.tsx
apps/registration/lib/api.ts

- Removes prior indication that users should check their email for their API key (no automated email is being sent by the system, so this was inaccurate)
- Also provides additional minor detail around how eligibility is determined, which complements the recent updates to the `/account` page

fix: remove email verbiage and clarify wording on registration success page

---

build-api-sdk.sh

This PR enables running `./build-api-sdk.sh` without explicit `sh ...`.

Fix build-api-sdk.sh

---

apps/api/package.json
packages/conversions/package.json
packages/eslint-config/package.json
packages/react/package.json
packages/react/src/hooks/buckets.ts
pnpm-lock.yaml

related to https://github.com/recallnet/js-recall/issues/330 and the issue about wagmi + type inference in `packages/react`

fix(ci): type `react` mutations | lock eslint version

---

apps/api/drizzle/0003_yielding_killraven.sql
apps/api/drizzle/meta/0003_snapshot.json
apps/api/drizzle/meta/_journal.json
apps/api/e2e/tests/trading.test.ts
apps/api/e2e/utils/api-types.ts
apps/api/openapi/openapi.json
apps/api/src/database/schema/trading/defs.ts
apps/api/src/routes/agent.routes.ts
apps/api/src/routes/trade.routes.ts
apps/api/src/services/trade-simulator.service.ts
packages/api-sdk/.speakeasy/gen.lock
packages/api-sdk/.speakeasy/gen.yaml
packages/api-sdk/.speakeasy/workflow.lock
packages/api-sdk/jsr.json
packages/api-sdk/package-lock.json
packages/api-sdk/package.json
packages/api-sdk/src/index.ts
packages/api-sdk/src/lib/config.ts
packages/api-sdk/src/mcp-server/mcp-server.ts
packages/api-sdk/src/mcp-server/server.ts
packages/api-sdk/src/models/operations/getapiagenttrades.ts
packages/api-sdk/src/models/operations/getapicompetitions.ts
packages/api-sdk/src/models/operations/getapicompetitionscompetitionid.ts
packages/api-sdk/src/models/operations/getapicompetitionsleaderboard.ts
packages/api-sdk/src/models/operations/getapicompetitionsstatus.ts
packages/api-sdk/src/models/operations/getapicompetitionsupcoming.ts
packages/api-sdk/src/models/operations/postapitradeexecute.ts

**What Changed:**
- Added `fromTokenSymbol` field to trades table to complement existing `toTokenSymbol`
- Updated trade execution to capture and store source token symbols
- Enhanced API responses to include both source and destination token symbols
- Updated OpenAPI documentation for trade execution and history endpoints  
- Added comprehensive E2E test coverage for the new field

feat: integrate fromTokenSymbol into trading schema and return types

---

apps/comps/app/competitions/page.tsx
apps/comps/app/create-agent/page.tsx
apps/comps/app/layout.tsx
apps/comps/components/agent-profile/index.tsx
apps/comps/components/bignumber/index.tsx
apps/comps/components/leaderboard-table.tsx
apps/comps/components/ongoing-competition.tsx
apps/comps/components/upcoming-competition.tsx
apps/comps/hooks/useAgent.ts
apps/comps/hooks/useLeaderboards.ts
apps/comps/lib/api-client.ts
apps/comps/types/agent.ts
apps/comps/types/enums.ts

- the default bg color was different than `bg-black`, so you could see a slight border-like rendering on pages. e.g., the area surrounding the landing page's video.
- the `/leaderboard` API was changed to singular, and now that it's live, the leaderboards component can properly use the data. 
- the top positions (1st, 2nd, 3rd) were displayed correctly, but numbers thereafter started at "3"...this has been fixed to properly increment values.
- some of the datapoints are also hidden, including the "change in rank" arrow and the "score". 
- note: the score exists in the API response, but we should ignore it for now since it's a somewhat arbitrary things until real ranks arrive.
- fixed the BigNumber component. it was causing issues for the leaderboard's `totalVolume` field when decimals …

feat(comps): leaderboard & minor fixups

---

.github/workflows/api-ci.yml
apps/api/.env.example
apps/api/.env.test
apps/api/e2e/utils/server.ts
apps/api/e2e/utils/test-helpers.ts
apps/api/src/config/index.ts
apps/api/src/config/swagger.ts
apps/api/src/index.ts
apps/api/trade-simulator-docker/docker-compose.yml
apps/api/trade-simulator-docker/instructions.md
apps/api/turbo.json

- Assuming we are going to continue using prefixed routing in the load balancer off of `https://api.competitions.recall.network/` (such as `sandbox`), we should standardize our approach that works both when running the server outside and inside containerization
- These changes primarily edit the main server file to absorb the routing, and uses the dependency injection `config` object, but also impacts the health check endpoint within the docker configuration, as well as ensuring our client is properly constructed in `apps/api/e2e`

feat: api prefix routing

---

apps/api/e2e/tests/agent.test.ts
apps/api/src/controllers/agent.controller.ts
apps/api/src/routes/agents.routes.ts

part of #509 
Very small PR here.  I'll keep adding to this as I find more places the api needs fixes to pagination and sorting, but feel free to review.

fix(api): include `hasMore` in /agents response

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

I've noticed some people using the "impact" section to list the specific changes that will be made.  That belongs more in the "Proposed Solution" section.  The impact section is more useful as input to deciding issue priority, so should be focused on how making this change will improve user experience, or on what the cost of *not* doing this will be.  I'm hoping this reword to the template will make that clearer

Update feature request template

---

apps/api/e2e/tests/user.test.ts
apps/api/e2e/utils/api-client.ts
apps/api/e2e/utils/api-types.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/src/controllers/user.controller.ts
apps/api/src/routes/user.routes.ts

Implements Issue #543 - adds endpoint for users to retrieve their own agent's API keys through the user interface.
- **New Endpoint**: `GET /user/agents/:agentId/api-key` 
- **Authentication**: SIWE session-based auth with ownership verification
- **Response Format**: `{ success, agentId, agentName, apiKey }`
- **Security**: Audit logging + reuses battle-tested admin decryption infrastructure
- **Controller**: New `getAgentApiKey` method in `UserController`
- **Route**: Added to `user.routes.ts` with comprehensive OpenAPI documentation
- **Types**: New `UserAgentApiKeyResponse` interface in API types
- **Infrastructure Reuse**: Leverages existing `AgentManager.getDecryptedApiKeyById()` 
- ✅ Ownership verification (user.id === agent.ownerId)
- ✅ Audit logging for credential access
- ✅ …

feat: allow users to fetch agent api keys

---

apps/api/e2e/tests/user.test.ts
apps/api/e2e/utils/api-client.ts
apps/api/e2e/utils/api-types.ts
apps/api/e2e/utils/test-helpers.ts
apps/api/openapi/openapi.json
apps/api/src/controllers/user.controller.ts
apps/api/src/database/repositories/agent-repository.ts
apps/api/src/routes/user.routes.ts
apps/api/src/services/agent-manager.service.ts
apps/api/src/types/index.ts

fixes: https://github.com/recallnet/js-recall/issues/497
This creates the `/api/user/competitions` endpoint that returns all competitions a user's agents are participating in. 
This adds to agent-repository with a `findUserAgentCompetitions` function that queries competitions for multiple agent IDs.
The agent manager service  has a new function `getCompetitionsForUserAgents`.  This gets all agents owned by a user, so that the `findUserAgentCompetitions` can be called with the user's agent ids.
The user controller method `getCompetitions` handles parsing request params/pagination/etc...
The testing is a little limited since there is still a limitation that only one comp can be active at a time.  There was a test helper added to quickly setup multiple users, agents, and competitions.

feat(api): add endpoint to get user's comps

---

apps/api/openapi/openapi.json
apps/api/src/controllers/agent.controller.ts
apps/api/src/controllers/request-helpers.ts
apps/api/src/routes/agents.routes.ts
apps/api/src/services/agent-manager.service.ts

part of: https://github.com/recallnet/js-recall/issues/509
part of: https://github.com/recallnet/js-recall/issues/426
The openapi spec was not correctly describing the `/api/agents/{agentId}/competitions` pagination and filtering querystring options.  This updates the spec and does a little bit of work to dry out parsing of paging and filtering parameters.

fix(api): openapi doc correctly describes spec

---

apps/api/e2e/tests/leaderboard.test.ts
apps/api/src/database/repositories/leaderboard-repository.ts

- Populate the "active" agents in the leaderboards `activeAgents` instead of hardcoding as zero.
- Use the `agent_rank` table to give us an accurate representation of "active" agents (see #458 for more info re: agent "status" and why this query works well for our needs).

fix(api): count total active agents

---

apps/api/e2e/tests/agent.test.ts
apps/api/e2e/utils/api-types.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/src/database/repositories/agent-repository.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/database/repositories/trade-repository.ts
apps/api/src/routes/agents.routes.ts
apps/api/src/routes/user.routes.ts
apps/api/src/services/agent-manager.service.ts
apps/api/src/types/index.ts

GitHub Issue #630 identified that the `/agents/:agentId/competitions` API endpoint was missing critical fields needed by the UI's table sorting component. 
The UI needed the following agent-specific metrics for each competition:
- `portfolioValue`: Agent's current portfolio value in the competition
- `pnl`: Agent's profit/loss amount and percentage  
- `totalTrades`: Number of trades made by the agent in that competition
- `bestPlacement`: Agent's rank and total participants in the competition
Following the existing `attachAgentMetrics` pattern, we implemented a per-competition metrics enhancement:
**Repository Layer:**
- Added `countAgentTradesInCompetition()` for competition-specific trade counting
- Added `getAgentCompetitionRanking()` for accurate ranking calculations
- Extended …

feat (api): fields added to /agents/:agentId/competitions and ensure sorting

---

apps/comps/components/agent-profile/comps-table.tsx
apps/comps/types/competition.ts

part of: https://github.com/recallnet/js-recall/issues/637
Connect front end agent profile page competitions table to the parts of the api that are supported currently

fix(comps): The agent profile page competition table shows data and can be sorted.

---

apps/registration/components/providers.tsx
apps/registration/hooks/useAuth.ts

- React Query caching behavior was caching nonces (single-use authentication tokens) between login attempts
- First attempt would fail due to nonce validation issues on the backend
- Second attempt would succeed because the same cached nonce was still valid within its time window
- The useNonce() hook was designed to reuse cached nonces instead of fetching fresh ones for each attempt
- Always fetch fresh nonces: Modified the authentication adapter to call refetchNonce() on every SIWE attempt instead of using cached data
- Disabled nonce caching: Set staleTime: 0 on the nonce query to prevent React Query from serving stale cached nonces
- Added cache invalidation: Implemented nonce cache cleanup after both successful and failed login attempts
- Improved error handling: Enhanced the login …

fix: resolve nonce generation in registration siwe process

---

apps/registration/components/mobile-sign-helper.tsx
apps/registration/components/mobile-wallet-enhancer.tsx
apps/registration/components/providers.tsx
apps/registration/lib/mobile-utils.ts

Implemented mobile-specific enhancements to address WalletConnect deep linking issues that prevent mobile wallet apps from properly opening for SIWE (Sign-In with Ethereum) authentication.
- Mobile users could connect their wallets successfully
- However, clicking "Sign Message" would not trigger the mobile wallet app to open
- This is a known limitation with WalletConnect v2 on mobile browsers
- Users experienced a "dead-end" where the sign button appeared but did nothing
- **Purpose**: Reliable mobile device detection for conditional behavior
- **Features**: 
- SSR-safe implementation with `typeof window` checks
- Comprehensive mobile device regex patterns
- Separate iOS and Android detection functions
- **Purpose**: Automatically reload page after wallet connection to prime …

fix: attempt to resolve registration signing on mobile with forced reload

---

apps/api/.env.example
apps/api/drizzle/0018_opposite_marrow.sql
apps/api/drizzle/0018_oval_lady_ursula.sql
apps/api/drizzle/meta/0018_snapshot.json
apps/api/drizzle/meta/_journal.json
apps/api/e2e/tests/email-verification.test.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/scripts/register-agent.ts
apps/api/scripts/register-user.ts
apps/api/src/config/index.ts
apps/api/src/controllers/email-verification.controller.ts
apps/api/src/database/repositories/email-verification-repository.ts
apps/api/src/database/schema/core/defs.ts
apps/api/src/database/schema/core/types.ts
apps/api/src/index.ts
apps/api/src/routes/email-verification.routes.ts
apps/api/src/services/agent-manager.service.ts
apps/api/src/services/email-verification.service.ts
apps/api/src/services/email.service.ts
apps/api/src/services/index.ts
apps/api/src/services/user-manager.service.ts
apps/api/turbo.json

Closes #437 
Closes #416 
- When a user is registered or updated, we check for the email and send a verification email
- When an agent is created or updated, we check for the email and send a verification email
- A token is stored on a new table called `email_verification_tokens`
- A new endpoint is created `GET /verify-email?token=${token}` for verifying the user (or agent)
- The user (or agent) is marked as verified (flag `is_email_verified` is set to `true`)
- That information is sent to Loops
- Two new envs are added: `LOOPS_API_KEY` and `LOOPS_TRANSACTIONAL_ID`. `LOOPS_TRANSACTIONAL_ID` is the id of the email template created on Loops web app
- A migration for  `email_verification_tokens` table and `is_email_verified` flag is added
- `EmailVerificationService` is responsible for …

feat: adds email verification

---

apps/api/src/controllers/agent.controller.ts
apps/api/src/services/trade-simulator.service.ts

Portfolio snapshots were being triggered for all agents in a competition in several scenarios where only a single agent's portfolio had actually changed. This created unnecessary database load and API calls that scaled poorly with competition size.
1. Trade Execution Optimization
- Before: Every trade → snapshot all agents in competition
- After: Every trade → snapshot only the trading agent
- File: apps/api/src/services/trade-simulator.service.ts
- Change: takePortfolioSnapshots() → takePortfolioSnapshotForAgent()
2. Portfolio Request Fallback Optimization
- Before: Agent requests portfolio with no snapshots → snapshot all agents
- After: Agent requests portfolio with no snapshots → snapshot only requesting agent
- File: apps/api/src/controllers/agent.controller.ts
- Change: …

fix: optimize portfolio snapshot type for trades and req fallback

---

apps/api/package.json
apps/api/scripts/reset-all-agent-api-keys.ts

- Adds simple utility script to allow administrator to reset all agent api keys in one go (so long as the `ROOT_ENCRYPTION_KEY` and `DATABASE_URL` are correctly set

feat: add reset agent api keys script

---

apps/api/src/controllers/agent.controller.ts

- Database stores snapshots in newest-first order
- Code incorrectly accessed the last element (oldest snapshot) instead of the first element (newest snapshot)

fix: portfolio endpoint to return latest snapshot data

---

apps/api/e2e/tests/price/multi-chain-provider.test.ts
apps/api/src/services/providers/multi-chain.provider.ts

- Multi chain provider previously logged `[object Object]` - for example, `[MultiChainProvider] Successfully found price for Solana token so111...: $[object Object]`
- This PR correctly uses the `price` field on the `price` object when logging from this provider

fix: correct price logging

---

apps/comps/components/competition-info.tsx

use "TBA" instead of "$0 USDC" for rewards

feat(comps): use 'tba' for rewards

---

.github/workflows/api-ci.yml
apps/api/.env.example
apps/api/.env.sandbox
apps/api/.env.test
apps/api/src/config/index.ts
apps/api/src/controllers/admin.controller.ts
apps/api/src/controllers/user.controller.ts
apps/api/turbo.json

Since the UI will gate access to API keys, a user cannot see their API key until they've verified their email + joined an active sandbox competition. But, we don't want the sandbox to send a Loops email because the production instance will handle user verification and UI behavior.
Thus, a prerequisite is that the user must be effectively marked as verified _in the sandbox_, else, they cannot join a competition. This must be available in production (the "sandbox" runs in NODE_ENV=production) and not purely in `NODE_ENV` development or test modes.
With this PR, we can use `ENABLE_AUTO_VERIFY_USER_EMAIL` in the sandbox, development, or test modes to auto-verify users.

feat(api): use env var for email auto-verify

---

apps/api/drizzle/0021_little_photon.sql
apps/api/drizzle/meta/0021_snapshot.json
apps/api/drizzle/meta/_journal.json
apps/api/e2e/tests/snapshots.test.ts
apps/api/src/controllers/agent.controller.ts
apps/api/src/database/repositories/balance-repository.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/database/repositories/price-repository.ts
apps/api/src/database/schema/trading/defs.ts
apps/api/src/services/balance-manager.service.ts
apps/api/src/services/competition-manager.service.ts
apps/api/src/services/price-tracker.service.ts
apps/api/src/services/providers/__tests__/batch-functionality.test.ts
apps/api/src/services/providers/dexscreener.provider.ts
apps/api/src/services/providers/multi-chain.provider.ts
apps/api/src/services/trade-simulator.service.ts
apps/api/src/types/index.ts

part of #620 
There are three groups of changes here to help with performance.
- Better database indexing
- Batching of dexscreener api calls 
- lower overhead in sql query result processing
There more improvements to be made, but this seems like a digestable size for a PR and will allow us to do more stress testing and iterate.

fix(api): performance improvements

---

apps/api/drizzle/0022_giant_gabe_jones.sql
apps/api/drizzle/meta/0022_snapshot.json
apps/api/drizzle/meta/_journal.json
apps/api/e2e/tests/competition.test.ts
apps/api/e2e/utils/api-client.ts
apps/api/e2e/utils/api-types.ts
apps/api/e2e/utils/test-helpers.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/src/controllers/admin.controller.ts
apps/api/src/controllers/admin.schema.ts
apps/api/src/controllers/competition.controller.ts
apps/api/src/database/schema/core/defs.ts
apps/api/src/routes/admin.routes.ts
apps/api/src/routes/competitions.routes.ts
apps/api/src/services/competition-manager.service.ts
apps/api/src/types/index.ts

Added optional `joinStartDate` and `joinEndDate` fields to competitions, allowing administrators to configure time-based restrictions on when agents can join pending competitions.
- **Optional constraints**: When dates are not provided, existing behavior is preserved (backward compatible)
- **Time-based validation**: Agents can only join competitions within the configured time window
- **Admin-only configuration**: Join dates can only be set during competition creation
- **Clear error messages**: Users receive specific error messages with actual opening/closing times
- Added `joinStartDate` and `joinEndDate` timestamp fields to `competitions` table
- Fields are nullable for backward compatibility
- Database migrations generated and applied
- **POST `/api/admin/competition/create`**: Added …

feat: use and enforce join start and end dates in competitions

---

apps/api/e2e/tests/admin.test.ts
apps/api/e2e/tests/agent.test.ts
apps/api/e2e/utils/api-client.ts
apps/api/openapi/API.md
apps/api/openapi/openapi.json
apps/api/src/controllers/admin.controller.ts
apps/api/src/controllers/admin.schema.ts
apps/api/src/controllers/agent.controller.ts
apps/api/src/routes/admin.routes.ts
apps/api/src/routes/agent.routes.ts
apps/api/src/types/index.ts
apps/comps/app/api/sandbox/agents/[agentId]/route.ts
apps/comps/components/agent-profile/index.tsx
apps/comps/hooks/useSandbox.ts
apps/comps/lib/sandbox-client.ts
apps/comps/types/admin.ts

closes https://github.com/recallnet/js-recall/issues/954
1. we remove the ability for an agent to update their "name". this is needed anways imo, else, we could have agents updating their names w/o user knowing.
2. add an admin API to update an agent
3. let the UI gatekeep agent name updates and sync them b/w "live" and "sandbox" servers

feat(comps): remove agent name update

---

apps/api/package.json
apps/api/scripts/backfill-stats.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/services/competition-manager.service.ts

@dtbuchholz Your PR looks great, but it looked like it needed to be rebased onto main to work correctly on the staging and prod databases.  
So this is mostly what you did in https://github.com/recallnet/js-recall/pull/933 but includes the `startingValue` data too.
I tested by downloading a backup yesterday's staging database, running api and app against it, then running the script.  After that all the agents data looks correct in the app.
closes #796

chore(api): updated backfill agent data and comps leaderboard script

---

apps/comps/components/agent-profile/index.tsx

The "share" button was under indexed and couldnt be clicked, so we increase the z-index to fix this

fix(comps): agent share button z index

---

apps/api/e2e/tests/trading.test.ts
apps/api/src/controllers/trade.controller.ts

Closes https://linear.app/recall-labs/issue/REC-49/bug-more-agents-in-the-snapshot-than-in-the-competition

fix: block trades of unregistered agents

---

.cursor/rules/org-general-practices.mdc
apps/api/src/controllers/trade.controller.ts
apps/api/src/services/__tests__/trade-simulator.constraints.test.ts
apps/api/src/services/price-tracker.service.ts
apps/api/src/services/trade-simulator.service.ts

No functional changes, just code cleanups.
* Commit 1: small cleanup to PriceTracker.getPrice to use an early return
* Commit 2: change TradeSimulator.executeTrade to throw on error instead of returning an error object
* Commit 3: Break up TradeSimulator.executeTrade into many smaller helper functions
* Commit 4: Cursor rule to keep functions small

chore: Small cleanups

---

apps/api/e2e/tests/competition.test.ts
apps/api/e2e/tests/trading.test.ts
apps/api/e2e/utils/api-types.ts
apps/api/e2e/utils/test-helpers.ts
apps/api/package.json
apps/api/scripts/backfill-comp-constraints.ts
apps/api/src/controllers/competition.controller.ts
apps/api/src/index.ts
apps/api/src/routes/admin.routes.ts
apps/api/src/services/competition-manager.service.ts

fixes #969 
Work also described here: https://linear.app/recall-labs/issue/REC-44/backend-follow-ups-for-trading-constraints-table-and-liquidity-rules

feat(api): contraints are returns via endpoints and always stored in db 

---

apps/comps/components/agent-avatar.tsx
apps/comps/components/agent-profile/credentials.tsx
apps/comps/components/agents-table/award-icon.tsx
apps/comps/components/agents-table/index.tsx
apps/comps/components/agents-table/rank-badge.tsx
apps/comps/components/competition-voting-banner.tsx
apps/comps/components/create-agent/agent-created.tsx
apps/comps/components/featured-competition.tsx
apps/comps/components/featured-competition/top-leaders-list.tsx
apps/comps/components/footer-section/index.tsx
apps/comps/components/identicon/index.tsx
apps/comps/components/leaderboard-table/index.tsx
apps/comps/components/navbar/index.tsx
apps/comps/components/participants-avatars.tsx
apps/comps/components/register-agent-block.tsx
apps/comps/components/rewards.tsx
apps/comps/components/siwe/index.tsx
apps/comps/components/trophy-badge/index.tsx
apps/comps/components/user-vote.tsx
packages/ui2/src/components/button.tsx
packages/ui2/src/styles/globals.css

- Fixed the comp rewards card not having a space between a word.
- Fixed colors to make sure trophies/ranks are consistent, and green / red / yellow use the figma colors.
- Made all of the agent rows in the global leaderboard and per-comp results clickable, vs a dedicated column for the agent profile.
- Global leaderboard tweaks to account for better spacing and responsiveness (i.e., hide the final 2 cols on smaller viewports).
- Fixed "jumpy" nav that shifted text upward upon clicking.
- Footer section updates.
- Fixed "add agent" button to prompt for wallet connection or agent creation, depending on user state.
- Fixed buttons being unable to have the "disable" cursor upon hover.

feat(comps): frontend cleanups

---

apps/api/trade-simulator-docker/Dockerfile
apps/comps/Dockerfile
docker-compose.yml

First pass of Docker Compose config to build both API and UI components and run them locally.
The Dockerfiles could have been more optimized but this version at least somewhat reduces the build time.

feat: docker compose for local testing

---

apps/api/e2e/setup.ts
apps/api/e2e/tests/portfolio-snapshots.test.ts
apps/api/src/config/index.ts
apps/api/src/services/portfolio-snapshotter.service.ts
apps/api/src/services/price-tracker.service.ts
apps/api/src/services/providers/__tests__/batch-functionality.test.ts
apps/api/src/services/providers/__tests__/multi-chain.provider.test.ts
apps/api/src/services/providers/dexscreener.provider.ts
apps/api/src/services/providers/multi-chain.provider.ts

Removes caching from MultiChainProvider and DexScreenerProvider.
Adds in-memory caching to PriceTracker, and cleans up usage of the database-layer cache
Ensures all access to price data goes through the PriceTracker, removes a caller that was bypassing it to read from the database cache directly.
I do think this was kind of a complicated and somewhat risky change, could probably use a close review

feat: Consolidate price caching in PriceTracker

---

apps/api/src/database/repositories/competition-repository.ts
apps/api/src/services/competition-manager.service.ts
apps/api/src/services/portfolio-snapshotter.service.ts

Mostly code cleanup, but there is one functional change: moving marking the competition as ended to be before we take the final snapshot.  This ensures that no last trades can sneak in after the final snapshot.
PR is composed of 3 independent commits, so you can review the functional change separately from the cleanups if you want

fix: Clean up endCompetition

---

apps/api/src/services/agent-manager.service.ts

closes https://linear.app/recall-labs/issue/REC-576/remove-legacy-api-key-validation-fallback-after-migration

fix(api): remove full table scan for agents

---

apps/api/e2e/tests/logging-metrics.test.ts
apps/api/e2e/tests/total-roi-calculation.test.ts
apps/api/src/database/repositories/agent-repository.ts
apps/api/src/database/repositories/agentscore-repository.ts
apps/api/src/database/repositories/leaderboard-repository.ts
apps/api/src/database/repositories/trade-repository.ts
apps/api/src/database/repositories/vote-repository.ts
apps/api/src/lib/repository-timing.ts
apps/api/src/services/agent-manager.service.ts
apps/api/src/services/agent-metrics-helper.ts
apps/api/src/types/agent-metrics.ts
apps/api/src/types/index.ts

They currently have wildly different implementations which creates a ton of code duplication and introduces the potential for bugs to arise from subtle differences between the two.
This does mean now that loading the metrics for a single agent will use an "in" statement in the underlying SQL query, but I'd like to be believe that the postgres query optimizer is smart enough that there's no perf overhead for an "in" query with only a single entry in the "in" statement...
Also includes some general code cleanups to the bulk query path to improve layering separation and add more explicit type information

feat: Implement getAgentMetrics in terms of getBulkAgentMetrics

---

apps/api/drizzle/0036_wandering_menace.sql
apps/api/drizzle/meta/0036_snapshot.json
apps/api/drizzle/meta/_journal.json
apps/api/e2e/tests/rewards.test.ts
apps/api/package.json
apps/api/scripts/insert-rewards.ts
apps/api/scripts/rewards-allocate.ts
apps/api/src/database/repositories/rewards-repository.ts
apps/api/src/database/schema/core/relations.ts
apps/api/src/database/schema/voting/defs.ts
apps/api/src/database/schema/voting/relations.ts
apps/api/src/services/rewards.service.ts

Closes [APP-136](https://linear.app/recall-labs/issue/APP-136/rewards-database-schema-changes)
We already had some rewards tables from [previous work ](https://github.com/recallnet/js-recall/pull/436). But those tables were pointing to `epochs` table. As of latest spec, we are implementing rewards by competition for TGE.
This PR:
- Removes epoch from `rewards`, `rewards_tree` and `rewards_roots` table, and add `competition_id`. This is a breaking change, but those tables are not used. So, not a big deal.
- Refactors `rewards-repository`, `rewards.service`, `rewards.test.ts` and scripts to accommodate that change

refactor: rewards should point to competitions and not epochs

---

apps/api/scripts/backfill-stats.ts
apps/api/scripts/competition-status.ts
apps/api/src/config/index.ts
apps/api/src/controllers/admin.controller.ts
apps/api/src/controllers/competition.controller.ts
apps/api/src/database/repositories/agent-repository.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/database/repositories/leaderboard-repository.ts
apps/api/src/database/schema/core/defs.ts
apps/api/src/database/schema/trading/defs.ts
apps/api/src/lib/handle-utils.ts
apps/api/src/middleware/active-comp-filter.middleware.ts
apps/api/src/services/agent-manager.service.ts
apps/api/src/services/competition-manager.service.ts
apps/api/src/services/vote-manager.service.ts
apps/api/src/types/index.ts

In preparation for implementing parts of our API in another app, to start with, we need to make the Drizzle schema shared code in its own package. This PR doesn't do that yet, but it untangles all the code in `apps/api/src/database/schema` from all other code in `apps/api`. This will allow us to move it to a new package in the next PR. In the process of doing this, it was clear there were places where the db schema should be the source of truth (mostly with enums that are used in other places in the app), so I refactored a bit to make it that way.

Isolate db schema code

---

apps/api/scripts/competition-status.ts
apps/api/scripts/delete-agent.ts
apps/api/scripts/end-competition.ts
apps/api/scripts/list-agents.ts
apps/api/scripts/reset-all-agent-api-keys.ts
apps/api/scripts/setup-competition.ts
apps/api/src/controllers/admin.controller.ts
apps/api/src/controllers/admin.schema.ts
apps/api/src/controllers/competition.controller.ts
apps/api/src/database/repositories/agent-repository.ts
apps/api/src/routes/admin.routes.ts
apps/api/src/services/agent-manager.service.ts

After the issues with the competition today, I went ahead and removed any attempts to get all agents with a single database query (`select * from agents;`).  
The exception is the scripts.  For scripts I replaced the get all agents with the new get agents with pagination, but the pagination allows for 1M agents, so the script still gets all the agents.
**Performance Optimization:** Replaced `getAllAgents()` method that was fetching all 145,000 agents from the database with targeted queries:
1. **Competition Controller** (`getLeaderboard`): Now only fetches agents participating in the specific competition using `getAgentsByIds()`
2. **Admin Controller**: 
- Competition leaderboard: Only fetches competition participants
- `listAllAgents` endpoint: Added pagination (default 50, max 1000) …

fix(api): remove full table scan query methods

---

apps/api/e2e/tests/competition.test.ts
apps/api/src/controllers/competition.controller.ts
apps/api/src/database/repositories/trade-repository.ts
apps/api/src/services/trade-simulator.service.ts

The `/competitions/:id` endpoint is currently doing a full scan of the `trades` table because we don't pass a limit to the method `services.tradeSimulator.getCompetitionTrades(competitionId)`. We only make that call because we need summary metrics (total trades, total volume, and # of unique tokens).
This PR adds a new method to simply calculate those metrics instead of doing "query all + in-memory computation"/

refactor(api): remove full scan & calculate summary metrics

---

.changeset/config.json
apps/api/trade-simulator-docker/Dockerfile
packages/db-schema/package.json

1. CI is failing to build the docker image because we explicitly include only a subset of packages—and the new db-schema package isn't included
2. we want to keep our db-schema package off of npm

fix: ci & db-schema package publishing

---

.husky/pre-commit
.husky/pre-push
package.json
pnpm-lock.yaml

- Adds husky for automated pre-commit and pre-push hooks  
- Configures lint-staged for automatic code formatting
- Implements quality checks (lint, format, build) before push
This implements [Linear AI-64](https://linear.app/recall-labs/issue/AI-64/add-basic-security-checks-to-js-recall): adding basic security checks to js-recall.
- Added husky and lint-staged as dev dependencies
- Created `.husky/pre-commit` hook for formatting staged files
- Created `.husky/pre-push` hook for quality checks (lint, format, build)
- Configured lint-staged in `package.json`

feat: git hooks for quality checks

---

apps/api/drizzle/0041_flippant_jazinda.sql
apps/api/drizzle/meta/0041_snapshot.json
apps/api/drizzle/meta/_journal.json
apps/api/scripts/backfill-agent-score.ts
apps/api/scripts/competition-status.ts
apps/api/src/database/repositories/agentscore-repository.ts
apps/api/src/database/repositories/balance-repository.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/services/agentrank.service.ts
apps/api/src/services/competition-manager.service.ts
apps/api/src/services/providers/__tests__/batch-functionality.test.ts
apps/api/src/services/providers/__tests__/dexscreener.provider.test.ts
apps/api/src/services/providers/__tests__/multi-chain.provider.test.ts
packages/db-schema/src/core/defs.ts

The goal of this PR is twofold: to make it so that `endCompetition` is resilient if the server crashes midway through processing it, and to make it resilient to `endCompetition` being run in parallel on the same competition by two different app servers / serverless functions at once.
The most straightforward way to do this would have been to do all the writes of `endCompetition` in a single transaction, but I was worried about how big and long running that transaction would be.  I was especially worried about locking out access to the `competition` table for a long time while that transaction runs, since that table is queried in many places throughout the app.  So I took a kind of hybrid approach, making the second half of `endCompetition` fully happen in a single transaction, but the …

feat: Make endCompetition transactional and idempotent

---

apps/comps/components/competition-info.tsx

closes [APP-85](https://linear.app/recall-labs/issue/APP-85/make-externalurl-field-visible-in-ui)
- if external URL is provided (and isn't example.com), we'll display `Read more about the official competition rules`
- we also enabled the "info" and "rules" tabs

feat(comps): competition rules & externalUrl

---

.github/workflows/release-prod.yml

[fixes error](https://github.com/recallnet/js-recall/actions/runs/17867824501/job/50814310428) in CI where the action is looking for a file at `/apps/comps/apps/comps/package.json` due to the `working-directory: apps/comps` line.
also, we have to temporarily disable vercel auto-deployments since everything after commit `04171dd` includes Boost in the UI.

fix(ci): vercel deployment | comment out code

---

apps/api/src/controllers/competition.controller.ts

we implemented a user-specific cache fix in [APP-418](https://linear.app/recall-labs/issue/APP-418/backend-api-returns-cached-data-for-hasvoted) ([PR](https://github.com/recallnet/js-recall/pull/1218/files#diff-003348c608e4df375ba22aa3d535d217103aca9cd7d7b07f3ecaf2e43641c20fR544)) that somehow got removed. this adds the code back.
note: we disabled this feature in production as a hotfix, so that's why we haven't heard about the problem.

fix(api): cache comps endpoint if incldues user-specific info

---

apps/api/trade-simulator-docker/Dockerfile

Fixes docker build issue, which is missing the `@recallnet/services` and `@recallnet/conversions` packages

fix(ci): build services package

---

apps/comps/components/competition-info.tsx
apps/comps/types/competition.ts

Hide the "rules" tab if it's a perps com

feat(comps): hide 'rules' tab for perps

---

.github/workflows/release-prod.yml

Fix CI action for vercel deployment by installing deps. See [here](https://github.com/recallnet/js-recall/actions/runs/18048746632/job/51365785912#step:7:846) for error.

fix(ci): install deps

---

apps/api/e2e/tests/perps-competition.test.ts
apps/api/src/services/competition.service.ts

This PR fixes a critical bug in the perps competition leaderboard where agents were being incorrectly ranked by portfolio value instead of Calmar ratio (risk-adjusted performance metric). The database query was correctly sorting by Calmar ratio, but the service layer was overriding this with a portfolio value sort.
The perps competition leaderboard is designed to rank agents by risk-adjusted performance using the Calmar ratio, which measures returns relative to maximum drawdown. However, the `CompetitionService` was incorrectly re-sorting the results by portfolio value after fetching the correctly-ordered data from the database.
This meant that agents with higher portfolio values would rank higher, even if they had worse risk-adjusted performance. This undermined the entire purpose of …

fix: resolve leaderboard competition endpoint to correctly use calmar ratio when constructing rankings

---

apps/api/src/lib/__tests__/retry-helper.test.ts

The retry helper test is [flaky](https://github.com/recallnet/js-recall/actions/runs/18047512613/job/51361745426), likely due to the non-deterministic jitter and the configured timeouts.

test(api): fix abort error in retry helper

---

apps/comps/components/agents-table/index.tsx

This PR fixes the frontend display issue where agents in perps competitions were shown in incorrect visual order (3rd, 1st, 2nd) despite having correct rank assignments from the backend.
The perps competition leaderboard was displaying agents out of order on the frontend. While the backend correctly:
1. Sorted agents by Calmar ratio (with fallback to equity for those without Calmar)
2. Assigned ranks correctly (1st, 2nd, 3rd)
The frontend was displaying them in the wrong visual order due to attempting to sort by `calmarRatio` field, which could be null for some agents.
The agents table component was initializing with different sort states for different competition types:
- Perps competitions: Sorted by `calmarRatio` descending
- Other competitions: Sorted by `rank` ascending
Since some …

fix: frontend competition table ordering for perps to use rank from backend

---

apps/api/e2e/tests/auto-start-competition.test.ts
apps/api/package.json
apps/api/scripts/auto-start-competitions.ts
apps/api/src/database/repositories/competition-repository.ts
apps/api/src/services/competition.service.ts
apps/api/src/services/trading-constraints.service.ts
packages/db/src/repositories/competition.ts

adds an "auto start" competition cron job, allowing competitions to both start and end without manual requiring admin API calls. closes [APP-200](https://linear.app/recall-labs/issue/APP-200/autostart-competition)

feat(api): auto-start comps

---

apps/comps/components/trophy-badge/index.tsx

Fixes APP-476
[Link to task ](https://linear.app/recall-labs/issue/APP-476/trophies-are-too-wide)

fix: adjust trophy widths to match design

---

apps/comps/app/competitions/page.tsx
apps/comps/hooks/useLeaderboards.ts
apps/comps/types/api.ts

We currently don't display the leaderboard carousel (it's controlled by an env var), but the fetch of the leaderboard happens anyway. This is on the main landing page, so this happens every time someone visits the site. The change will only load the data if it will be displayed.

Don't fetch leaderboard data if it won't be displayed

---

apps/comps/components/unified-leaderboard/skill-detail/skill-detail-page.tsx

fixes the perps leaderboard to show "agent" instead of "model". closes [app-562](https://linear.app/recall-labs/issue/APP-562/fix-ui-showing-incorrect-model-instead-of-agent-in-perp-future)

fix(comps): logic to display `agent` not `model`

---

apps/api/vitest.config.ts
apps/comps/lib/db.ts
apps/comps/rpc/router/competitions/get-agents.ts
apps/comps/vitest.config.ts
packages/conversions/vitest.config.ts
packages/db/vitest.config.ts
packages/rewards/examples/test-case-with-ties.json
packages/rewards/examples/test-case.json
packages/rewards/package.json
packages/rewards/scripts/verify.ts
packages/rewards/src/helpers.test.ts
packages/rewards/vitest.config.ts
packages/services/src/__tests__/trade-simulator.constraints.test.ts
packages/services/src/providers/__tests__/chain-override.test.ts
packages/services/src/providers/__tests__/dexscreener.provider.batch.test.ts
packages/services/src/providers/__tests__/dexscreener.provider.test.ts
packages/services/src/providers/__tests__/multi-chain.provider.batch.test.ts
packages/services/src/providers/__tests__/multi-chain.provider.test.ts
packages/services/src/providers/__tests__/price-tracker.service.batch.test.ts
packages/services/vitest.config.ts
pnpm-lock.yaml
turbo.json

We had a strange situation that I just discovered that resulted in som packages not compiling when running `pnpm dev` and tests running and passing even though they contained typescript compilation errors. This was caused by these factors:
- Vitest, by default, doesn't check that your typescript written test actually compile and will just transpile and run them. These tests may still run an succeed despite the typescript errors in the source file.
- We run  our `dev` mode using `tsc --watch` which compiles all files, including test files, so compilation was failing for some tests in dev mode.
- We run `build` using `tsup` which ignores test files, so we were never aware of the typescript problems in the tests.
This PR cleans all that up by making Vitest fail if there are typescript errors …

Tests tsc + rewards package fixes

---

apps/comps/public/data/benchmark-leaderboard.json

Makes the following updates:
- "Crypto Trading - 7-day P&L" -> "Crypto Paper Trading"
- "Live Trading - Perpetual Futures" -> "Crypto Perpetual Futures Trading"
Closes [APP-561](https://linear.app/recall-labs/issue/APP-561/update-copy-for-trading-skills).

feat(comps): copy update for agent comps

---

apps/comps/app/competitions/[id]/page.tsx
apps/comps/components/timeline-chart/timeline-chart.tsx
apps/comps/components/timeline-chart/types.ts

Removes the portfolio chart button and associated scroll reference from the competition page. Cleans up timeline chart component by removing unused scroll functionality.

chore: cleanup portfolio chart button 

---

apps/comps/app/layout.tsx
packages/ui2/src/components/tabs.tsx
packages/ui2/src/styles/globals.css

Fixes horizontal overflow on mobile and small screen sizes (APP-506) by preventing the hero carousel from causing page-wide scrolling.
- Add `overflow-x: clip` to html/body to prevent horizontal scroll
- Change TabsList from fixed height to min-height for proper wrapping on mobile

fix(ui): prevent horizontal overflow on mobile screens

---

apps/comps/components/navbar/index.tsx
apps/comps/components/privy-auth-button.tsx

https://linear.app/recall-labs/issue/APP-469/missing-hover-states
Note: I am not good with front-end design stuff!!! I tried to follow the design as close as possible (with the help of ai) 
- Added hover states to navbar navigation items with color-specific glow effects (yellow for COMPETITIONS, green for LEADERBOARDS)
- Added hover background (`gray-900/50`) to logo, boost display, and profile button
- Conditional hover effects on profile button (disabled when on `/profile` page)
- Conditional left border on profile section (only shows when boost is visible)
- Refactored nav items to use data-driven color configuration

feat: add navbar hover states

---

apps/comps/components/hexagon/index.tsx
apps/comps/components/trophy-badge/index.tsx

Fix trophy centering on agent profile and table

fix: Center hexagon trophy images

---

apps/api/src/services/index.ts
apps/comps/components/agents-table/index.tsx
apps/comps/lib/services.ts
apps/comps/rpc/router/boost/claim-staked-boost.ts
apps/comps/rpc/router/boost/index.ts
packages/services/src/boost.ts

Changes the logic of the "Start boosting" button that allocates some boosts to the user, with a feature flag. We now should consider the stakes to determine how much boost to allocate. 
Closes [APP-599](https://linear.app/recall-labs/issue/APP-599/update-activate-boost-logic-for-tge)
This was manually tested by inserting stakes in the database, and manually changing the code to activate one logic or the other.

feat: updates activate boost logic
