.changeset/breezy-impalas-shake.md, packages/fvm/README.md, packages/sdk/README.md
initial release for @recallnet packages
=> chore: publish initial release

.changeset/config.json
Forgot to do this in the last PR
=> ignore faucet from changeset

apps/faucet/app/_components/request-tokens-form.tsx
Just fixes a couple visual things that were bothering me.
=> Better faucet form layout

package.json, packages/eslint-config/package.json, pnpm-lock.yaml
Hopefully fix build cache issue.
=> Update to newer turbo version

apps/portal/app/account/_components/account.tsx, apps/portal/app/account/_components/approval.tsx, apps/portal/app/account/_components/approvals-to.tsx, packages/bigint-utils/src/constants.ts, packages/bigint-utils/src/conversions.ts, packages/sdkx/src/react/buckets.ts, packages/sdkx/src/react/credits.ts, packages/ui/src/recall/buy-credits-dialog.tsx, packages/ui/src/recall/wallet.tsx, turbo.json
Cleans up and fixes bugs in the conversion and display of various account values like balance, credit, etc. Snuck a couple other little improvements in there as well.
Fixes #95
=> Account conversion and display fixes

apps/portal/app/buckets/[address]/_components/add-object-dialog.tsx, apps/portal/app/buckets/[address]/_components/bucket.tsx, packages/bigint-utils/src/conversions.ts
closes #128 
closes #125 
closes #123 
closes #122 
closes #119
=> Fixes for a few nits and bugs

packages/ui/src/recall/wallet.tsx
Quick fix to make sure people are connected to Recall network. There might be a more user friendly way of doing this, and I'll explore that if needed, but this is a quick fix that works immediately.
=> Always switch back to recall network

packages/agent-toolkit/package.json, packages/bigint-utils/package.json, packages/fvm/package.json, packages/mcp/package.json, packages/sdk/package.json
Should be a quick one to just standardize the lint script across all packages/
=> Fix all lint scripts

README.md, packages/conversions/README.md
Meant to get these into the last PR but forgot.
=> couple changes to clarify use of conversions package

apps/api/scripts/competition-status.ts, apps/api/scripts/generate-secrets.ts, apps/api/scripts/initialize-db.ts, apps/api/scripts/list-teams.ts, apps/api/scripts/setup-admin.ts, apps/api/scripts/setup-competition.ts, apps/api/scripts/setup-everything.ts, apps/api/src/controllers/account.controller.ts, apps/api/src/controllers/competition.controller.ts, apps/api/src/database/repositories/competition-repository.ts, apps/api/src/database/repositories/price-repository.ts, apps/api/src/services/team-manager.service.ts, apps/api/tsconfig.json
Enabled a Typescript compiler option I think is very useful and safe... When you access data by index, in an array for example, the result can possibly be undefined. This is more correct, and the standard used in the rest of the repo.
IMPORTANT: Logic changes here to deal with possibly undefined values.
=> Enable ts undefined for indexed access, deal with undefined values

apps/api/openapi/API.md, apps/api/openapi/openapi.json, apps/api/scripts/clean-db.ts, apps/api/scripts/drop-all-tables.ts, apps/api/scripts/generate-secrets.ts, apps/api/scripts/initialize-db.ts, apps/api/scripts/setup-everything.ts, apps/api/src/routes/account.routes.ts, apps/api/src/routes/trade.routes.ts
#265 missed a few place were the openapi spec needs to be updated for code generators to consume the spec.
This PR fixes those, and enables sdk code generation tools to work with our spec.
=> fix(api): cleanup openapi spec

apps/api/e2e/tests/auth.test.ts, apps/api/e2e/utils/api-client.ts, apps/api/e2e/utils/api-types.ts, apps/api/e2e/utils/siwe-utils.ts, apps/api/package.json, pnpm-lock.yaml
- Adds e2e test cases to suite to confirm expected siwe login/logout/auth functionality
=> feat: add auth tests

.dockerignore, apps/api/trade-simulator-docker/Dockerfile, apps/api/trade-simulator-docker/docker-compose.yml, apps/api/trade-simulator-docker/instructions.md
This PR fixes Dockerfile and docker-compose.yml
Close #355
=> Fix docker build

apps/api/e2e/tests/leaderboard.test.ts, apps/api/e2e/utils/api-types.ts, apps/api/openapi/API.md, apps/api/openapi/openapi.json, apps/api/src/controllers/leaderboard.controller.ts, apps/api/src/database/repositories/leaderboard-repository.ts, apps/api/src/routes/leaderboard.routes.ts, apps/api/src/services/agent-manager.service.ts, apps/api/src/types/index.ts
=> feat(api): add vote-related metrics to leaderboard api

apps/api/e2e/tests/user.test.ts, apps/api/e2e/utils/api-client.ts, apps/api/e2e/utils/api-types.ts, apps/api/src/controllers/request-helpers.ts, apps/api/src/controllers/user.controller.ts, apps/api/src/database/repositories/agent-repository.ts, apps/api/src/services/agent-manager.service.ts
=> feat(api): add pagination and sorting to the endpoint for getting a user's agents

apps/api/drizzle/0007_big_gargoyle.sql, apps/api/drizzle/0007_complete_blindfold.sql, apps/api/drizzle/meta/0007_snapshot.json, apps/api/drizzle/meta/_journal.json, apps/api/src/database/schema/core/defs.ts, apps/api/src/database/schema/core/relations.ts, apps/api/src/database/schema/core/types.ts, apps/api/src/database/schema/index.ts, apps/api/src/database/schema/ranking/defs.ts, apps/api/src/database/schema/ranking/relations.ts, apps/api/src/database/schema/ranking/types.ts
=> feat: adds agent rank tables

apps/comps/components/featured-competition.tsx
See here: for details https://github.com/recallnet/js-recall/pull/570#issuecomment-2970899272
=> fix(comps): comp leaders ordered by position

packages/ui2/src/styles/globals.css
Fixes https://github.com/recallnet/js-recall/issues/583
=> fix(comps): remove light mode

apps/api/e2e/tests/agent.test.ts, apps/api/e2e/tests/competition.test.ts, apps/api/src/controllers/competition.controller.ts, apps/api/src/controllers/request-helpers.ts, apps/api/src/database/repositories/agent-repository.ts, apps/api/src/lib/sort.ts, apps/api/src/routes/competitions.routes.ts, apps/api/src/services/agent-manager.service.ts, apps/api/src/services/competition-manager.service.ts, apps/api/src/services/index.ts, apps/api/src/types/sort/agent.ts, apps/api/src/types/sort/shared.ts
- Closes #621 
- Related to #620 (and sorting _with_ computed value in post-query logic)
=> fix(api): `compititions/:id/agents` query sorting and pagination

apps/api/.env.example, apps/api/.env.test, apps/api/trade-simulator-docker/.env.example
- Found this error when setting up the staging
=> fix: correct env where represented in test and example file

apps/api/e2e/tests/user.test.ts
=> test(api): test for user comps status sort

apps/comps/components/leaderboard-table/index.tsx, apps/comps/components/leaderboard/index.tsx, apps/comps/components/leaderboard/loading.tsx, apps/comps/components/pagination/index.tsx
=> Rafael/leaderboard v1.2

apps/api/e2e/tests/user.test.ts, apps/api/openapi/openapi.json, apps/api/src/controllers/user.controller.ts, apps/api/src/routes/user.routes.ts, apps/api/src/services/agent-manager.service.ts
=> fix(api): return correct http status code when user attempts to create duplicated agent name

apps/comps/app/profile/page.tsx, apps/comps/components/create-agent/index.tsx, apps/comps/components/user-agents/agent-card.tsx, apps/comps/components/user-agents/agents-summary.tsx, apps/comps/components/user-agents/index.tsx, packages/ui2/src/components/card.tsx
=> fix(comps): fixed wrong agent list layout

.github/workflows/api-ci.yml
depends on https://github.com/recallnet/js-recall/pull/728 (for the CI to pass)
=> chore(ci): add check for bad drizzle migrations

apps/api/src/config/swagger.ts
- Hard-codes sandbox api for swagger
=> chore: quick patch for sandbox swagger option

apps/comps/app/competitions/[id]/page.tsx, apps/comps/app/layout.tsx, apps/comps/components/competition-voting-banner.tsx, apps/comps/components/create-agent/basics-step.tsx, apps/comps/components/create-agent/socials-step.tsx, apps/comps/components/navbar/index.tsx, packages/ui2/src/components/form.tsx
https://github.com/recallnet/js-recall/pull/762#pullrequestreview-2966641353
=> fix(comps): remaining UI issues from https://github.com/recallnet/js-recall/pull/762

apps/comps/components/agent-profile/index.tsx, apps/comps/components/competitions-table.tsx, apps/comps/components/profile-skeleton.tsx, apps/comps/components/user-votes/votes-table.tsx
=> fix: accurate profile skeleton

apps/comps/components/leaderboard-table/index.tsx, apps/comps/components/leaderboard/index.tsx
=> fix: leaderboard diffs

apps/api/drizzle/0019_sweet_mockingbird.sql, apps/api/drizzle/meta/0019_snapshot.json, apps/api/drizzle/meta/_journal.json, apps/api/e2e/tests/user.test.ts, apps/api/e2e/utils/api-types.ts, apps/api/scripts/competition-status.ts, apps/api/src/config/index.ts, apps/api/src/database/repositories/competition-repository.ts, apps/api/src/database/repositories/leaderboard-repository.ts, apps/api/src/database/schema/core/defs.ts, apps/api/src/database/schema/trading/defs.ts, apps/api/src/services/agent-manager.service.ts, apps/api/src/services/competition-manager.service.ts, apps/comps/components/user-agents/agents-summary.tsx, apps/comps/components/user-agents/index.tsx, apps/comps/types/agent.ts
fixes: https://github.com/recallnet/js-recall/issues/732
Ended up making a biggger change here than might have been initially expected, because some of the perf gains of #703 would have been reverted otherwise.
=> fix(api): user/agents stats response shape

apps/api/src/services/providers/dexscreener.provider.ts, apps/comps/wagmi-config.ts
closes https://github.com/recallnet/js-recall/issues/740
=> feat: OKX to the top

apps/comps/components/agent-profile/agent-image.tsx, apps/comps/components/create-agent/image-preview.tsx, apps/comps/components/create-agent/socials-step.tsx, apps/comps/components/image-input/index.tsx, apps/comps/components/user-info/ProfilePicture.tsx, apps/comps/utils/url.ts
=> fix: fixed url issue on create agent

apps/api/src/services/email.service.ts
@dtbuchholz I was reviewing #874 and these cahnges made it easy to run through the ui states manually.  Thoughts?
=> feat(api): log email verify link to console if in dev mode

apps/registration/.env.example, apps/registration/app/maintenance/layout.tsx, apps/registration/app/maintenance/page.tsx, apps/registration/middleware.ts, apps/registration/turbo.json
- Enforces maintenance mode page when NEXT_PUBLIC_MAINTENANCE_MODE=true
=> temp: implement maintenance mode on registration site

apps/comps/app/api/sandbox/_lib/sandbox-config.ts, apps/comps/app/api/sandbox/_lib/sandbox-response.ts, apps/comps/app/api/sandbox/agents/[agentId]/competitions/route.ts, apps/comps/components/agent-profile/credentials.tsx, apps/comps/components/create-agent/agent-created.tsx, apps/comps/hooks/useUnlockKeys.ts, apps/comps/lib/sandbox-client.ts
- Fixes error where you had to "unlock keys" but nothing happened; thus, you couldnt access your API keys
- Improves flow so that you only have to "unlock keys" once, and then, they'll always show
=> fix(comps): agent API key unlock flow

apps/comps/components/create-agent/basics-step.tsx
=> Don't submit form when clicking back

apps/comps/components/agents-table/index.tsx
=> Remove max height on agents table 

apps/api/src/index.ts
=> fix(api): shutdown listners gracefully close

apps/api/src/database/repositories/competition-repository.ts
refactor the SQL statement in `getLatestPortfolioSnapshots`
=> fix(api): latest snapshots query

apps/api/.env.test, apps/api/src/database/repositories/competition-repository.ts
refactor `get24hSnapshots` with more performant SQL
=> refactor(api): improve 24h query

apps/api/e2e/tests/competition.test.ts, apps/api/src/controllers/admin.controller.ts
Closes https://github.com/recallnet/js-recall/issues/971
We were not checking if agents existed and were active before starting a competition
=> fix: validate agents when starting comp

apps/api/src/database/repositories/balance-repository.ts, apps/api/src/database/repositories/trade-repository.ts, apps/api/src/services/balance-manager.service.ts, apps/api/src/services/trade-simulator.service.ts, apps/api/src/types/index.ts
builds on https://github.com/recallnet/js-recall/pull/1019
closes https://linear.app/recall-labs/issue/REC-237/atomic-trade-execution
=> feat: Make all db updates for finalizing a trade atomic

apps/api/src/controllers/competition.controller.ts, apps/api/src/database/repositories/competition-repository.ts, apps/api/src/services/vote-manager.service.ts
=> chore(api): reduce 4N query to 3

apps/api/src/controllers/agent.controller.ts, apps/api/src/database/repositories/agentscore-repository.ts, apps/api/src/database/repositories/competition-repository.ts
=> chore(api): refactor mutli query tx into single query

apps/api/e2e/tests/logging-metrics.test.ts, apps/api/e2e/tests/trading.test.ts, apps/api/e2e/utils/api-client.ts, apps/api/e2e/utils/api-types.ts, apps/api/openapi/API.md, apps/api/openapi/openapi.json, apps/api/src/controllers/agent.controller.ts, apps/api/src/routes/agent.routes.ts
it's redundant of the balance endpoint
=> feat: Remove portfolio endpoint

apps/comps/components/competition-card.tsx, apps/comps/components/competition-state-summary.tsx
=> feat(comps): add CompetitionStateSummary component to display competition status

apps/comps/components/competition-info.tsx, apps/comps/components/competition-state-summary.tsx, apps/comps/components/join-competition-button.tsx, apps/comps/types/competition.ts
- no limit
- max included, but still open
- max has been hit
- comp cards show the participant summary
=> feat(comps): limit registration

apps/comps/components/competition-info.tsx
=> feat(comps): info/rules tabs

apps/api/e2e/utils/api-client.ts, apps/api/e2e/utils/api-types.ts, apps/api/src/database/repositories/price-repository.ts, apps/api/src/services/price-tracker.service.ts, apps/api/src/services/providers/__tests__/dexscreener.provider.test.ts, apps/api/src/services/providers/__tests__/multi-chain.provider.test.ts, apps/api/src/services/providers/dexscreener.provider.ts, apps/api/src/services/providers/jupiter.provider.ts, apps/api/src/services/providers/multi-chain.provider.ts, apps/api/src/services/providers/noves.provider.ts, apps/api/src/services/providers/raydium.provider.ts, apps/api/src/types/index.ts
builds on https://github.com/recallnet/js-recall/pull/1076.
Simple cleanup of dead code
=> chore: Remove a bunch of unused functions from the price fetching stack

.github/workflows/api-ci.yml, apps/api/README.md, apps/api/e2e/tests/competition.test.ts, apps/api/e2e/utils/api-types.ts, apps/api/src/config/index.ts, apps/api/src/controllers/competition.controller.ts, apps/api/src/routes/competitions.routes.ts, apps/api/trade-simulator-docker/.env.example
builds on https://github.com/recallnet/js-recall/pull/1096
=> feat: Remove unused env vars and remove snapshot interval from rules response

apps/comps/components/unified-leaderboard/skill-detail/skill-detail-page.tsx, apps/comps/public/data/benchmark-leaderboard.json
- Ref https://github.com/recallnet/js-recall/pull/1138
=> feat: update the leaderboards with agent rank

apps/comps/public/data/benchmark-leaderboard.json
- Cherry-picks 64bceea5e5736199fe76ce610a865ffed1c63919 from main into prod-latest
=> fix: used old leaderboard stats (#1154)

apps/api/src/database/repositories/competition-repository.ts
this _might_ fixes [this sentry identified error](https://recallnet.sentry.io/issues/6860320749/?project=4509872367534080&query=is%3Aunresolved&referrer=issue-stream). there's a `length` property being accessed incorrectly. the real issue is probably deeper, but this _should_ help with debugging.
=> fix(api): handle 'length' access in 'get24hSnapshotsImpl'

apps/api/src/database/repositories/competition-repository.ts, apps/api/src/services/competition-manager.service.ts
@carsonfarmer @dtbuchholz This should help us track down the issue with staging
=> chore: update logging

apps/api/src/controllers/__tests__/request-helpers.test.ts, apps/api/src/controllers/competition.controller.ts, apps/api/src/controllers/request-helpers.ts
closes [APP-418](https://linear.app/recall-labs/issue/APP-418/backend-api-returns-cached-data-for-hasvoted)
=> fix(api): cache comps api per-user ID

apps/api/e2e/tests/admin.test.ts, apps/api/src/database/db.ts, apps/api/src/database/repositories/competition-repository.ts, apps/api/src/database/repositories/trading-constraints-repository.ts, apps/api/src/services/__tests__/competition-manager-create.test.ts, apps/api/src/services/competition-manager.service.ts, apps/api/src/services/trading-constraints.service.ts
Builds on https://github.com/recallnet/js-recall/pull/1221
=> feat: Make createCompetition atomic

apps/comps/providers/session-provider.tsx
closes [APP-425](https://linear.app/recall-labs/issue/APP-425/lazy-create-embedded-wallets-for-privy-users-if-it-doesnt-exist)
=> fix(comps): create embedded wallet if not exists

.github/workflows/release-prod.yml
closes [APP-412](https://linear.app/recall-labs/issue/APP-412/configure-vercel-comps-deployment-to-use-tags).
=> feat(ci): deploy to vercel prod on tags

apps/api/src/controllers/__tests__/request-helpers.test.ts, apps/api/src/controllers/admin.controller.ts, apps/api/src/controllers/auth.controller.ts, apps/api/src/controllers/request-helpers.ts, apps/api/src/controllers/user.controller.ts, apps/api/src/lib/error-utils.ts, apps/api/src/services/admin.service.ts, apps/api/src/services/agent.service.ts, apps/api/src/services/index.ts, apps/api/src/types/index.ts
Builds on https://github.com/recallnet/js-recall/pull/1265
=> chore: Move business logic from AdminController registerUser and registerAgent functions down into Service layer

apps/api/scripts/seed-perps-competition.ts, apps/comps/components/agent-profile/comps-table.tsx, apps/comps/components/agents-table/index.tsx, apps/comps/components/competition-info.tsx, apps/comps/components/leaderboard/index.tsx, apps/comps/types/agent.ts, apps/comps/types/competition.ts
This pull request implements frontend display of Calmar Ratio and risk metrics for perpetual futures competitions. The backend already provides these metrics - this PR updates the UI to display them appropriately across all relevant views.
**File: `apps/comps/types/agent.ts`**
- Added risk metrics fields to `AgentCompetition` interface:
- `calmarRatio?: number | null`
- `simpleReturn?: number | null` 
- `maxDrawdown?: number | null`
- `hasRiskMetrics?: boolean`
**File: `apps/comps/types/competition.ts`**
- Made `totalVolume` optional in stats object to handle perps competitions that don't have this metric
**File: `apps/comps/components/agents-table/index.tsx`**
- Implemented conditional display based on competition type
- For perps competitions:
- Shows "Calmar Ratio" as the primary …
=> feat (comps): update table displays in frontend to accommodate new risk-adjusted returns metric

.changeset/config.json
- Ignores recallnet/services is changesets configuration
=> fix: ignore recallnet/services

apps/api/trade-simulator-docker/Dockerfile
Adds missing package.json files for services, conversions
=> fix(ci): add package.json for services, conversions

apps/api/src/services/providers/perps/symphony-perps.provider.ts
Improves logging so we can see the full error
=> chore(api): log full err in symphony logging

apps/api/src/services/calmar-ratio.service.ts, apps/comps/components/agent-profile/comps-table.tsx, apps/comps/components/agents-table/index.tsx
- Removes annualization altogether in calmar service (api)
- Ensure rounding for risk metrics in frontend
=> fix: remove annualization and ensure risk metrics rounding

apps/comps/app/competitions/page.tsx
Fixes APP-453
[Link to linear task. ](https://linear.app/recall-labs/issue/APP-453/main-supporting-ctas-need-to-change)
=> fix: update button color to match design

apps/comps/app/layout.tsx
Add Cookie3 analytics to the app site.
=> feat: cookie3 analytics

apps/comps/components/unified-leaderboard/hub/skill-overview-card.tsx, apps/comps/components/unified-leaderboard/hub/unified-leaderboard-hub.tsx, apps/comps/components/unified-leaderboard/skill-detail/skill-detail-page.tsx, apps/comps/utils/competition-utils.ts
Hides new skills, in case there are no agents in the global ranks, yet
=> fix(comps): don't render skill if no agents

apps/comps/components/agents-table/index.tsx
Closes [APP-589](https://linear.app/recall-labs/issue/APP-589/ui-comps-leaderboard-missing-pnl-change)
=> fix(comps): add pnl & percent columns

apps/comps/components/footer-section/index.tsx
=> Update font weight

apps/comps/components/agent-profile/best-placement.tsx, apps/comps/components/agent-profile/index.tsx, apps/comps/components/user-agents/index.tsx, apps/comps/components/user-competitions.tsx, apps/comps/components/user-info/index.tsx, apps/comps/components/user-votes/index.tsx
This PR is meant to close the following issues:
- https://linear.app/recall-labs/issue/APP-477/fix-font-weight
- https://linear.app/recall-labs/issue/APP-466/fix-font-weights
=> fix: font weights in user profile and agent card

apps/comps/components/privy-auth-button.tsx, apps/comps/components/user-info/index.tsx
Update username in nav bar to mono
=> fix:wrong font for user profile navbar

apps/comps/components/agent-profile/agent-image.tsx, apps/comps/components/agent-profile/edit-field.tsx, apps/comps/components/agent-profile/edit-skills-field.tsx, apps/comps/components/edit-button.tsx, apps/comps/components/user-info/ProfilePicture.tsx, apps/comps/components/user-info/index.tsx
Update edit icon with hover state and tool tip - PLEASE VERIFY - I can't actually see this in action because I don't have data locally and can't log in on the staging preview. Please pull down this branch and test.
=> fix:Update edit icon with hover state

apps/comps/components/agent-profile/index.tsx
make the line dividing the box shorter.
=> fix: Line too long in agent profile

apps/api/e2e/setup.ts, apps/api/e2e/tests/perps-competition.test.ts, apps/api/e2e/utils/mock-hyperliquid-server.ts, apps/api/e2e/utils/mock-symphony-server.ts, apps/api/e2e/utils/test-setup.ts, packages/db/src/repositories/competition.ts, packages/db/src/repositories/perps.ts, packages/services/src/__tests__/perps-data-processor.test.ts, packages/services/src/lib/__tests__/circuit-breaker.test.ts, packages/services/src/lib/circuit-breaker.ts, packages/services/src/perps-data-processor.service.ts, packages/services/src/providers/__tests__/hyperliquid-perps.provider.test.ts, packages/services/src/providers/__tests__/perps-provider.factory.test.ts, packages/services/src/providers/perps-provider.factory.ts, packages/services/src/providers/perps/hyperliquid-perps.provider.ts, packages/services/src/providers/perps/symphony-perps.provider.ts, packages/services/src/types/perps.ts
This PR adds comprehensive support for Hyperliquid as a data provider for perpetual futures competitions, including production implementation and extensive E2E testing infrastructure. Hyperliquid is a high-performance L1 blockchain DEX offering fully on-chain perpetual futures trading with deep liquidity and low latency.
- 741 lines of production code implementing the `IPerpsDataProvider` interface
- Supports account summaries, positions, and transfer history fetching
- Multi-asset support (USDC, BTC, ETH, SOL) for transfer detection
- Retry logic with exponential backoff for resilience
- 1% sampling rate for raw data storage (prevents database bloat)
- Full Sentry integration with breadcrumbs and error tracking
- Wallet address masking for privacy in logs
- Modified …
=> feat (services): add hyperliquid provider, alter perps interface, add factory support + tests

apps/comps/app/competitions/[id]/page.tsx, apps/comps/components/agent-profile/comps-table.tsx, apps/comps/components/agents-table/index.tsx, apps/comps/components/unified-leaderboard/hub/unified-leaderboard-hub.tsx, apps/comps/components/unified-leaderboard/skill-detail/skill-detail-page.tsx, apps/comps/utils/competition-utils.ts, packages/ui2/src/components/table.tsx
Minor UI fixes to the global leaderboard, comps leaderboard, and agent profile table. Closes [APP-606](https://linear.app/recall-labs/issue/APP-606/fix-global-leaderboard-models-comp-result-sorting-and-comp-table).
=> fix(comps): comps table sort, style, & leaderboard

packages/staking-contracts/src/rewards-allocator.ts, packages/staking-contracts/src/rewards-claimer.ts, packages/staking-contracts/test/rewards-allocator.test.ts, packages/staking-contracts/test/rewards-claimer.test.ts
fixes [timeout](https://github.com/recallnet/js-recall/actions/runs/18324012087/job/52183850466?pr=1381#step:9:387) in unit tests due to viem's internal RPC retry logic
=> feat(contracts): opt override http viem retries
